.PHONY: clean All

All:
	@echo "----------Building project:[ AdoptedAlgorithm - Debug ]----------"
	@cd "AdoptedAlgorithm" && "$(MAKE)" -f  "AdoptedAlgorithm.mk"
clean:
	@echo "----------Cleaning project:[ AdoptedAlgorithm - Debug ]----------"
	@cd "AdoptedAlgorithm" && "$(MAKE)" -f  "AdoptedAlgorithm.mk" clean
