.PHONY: clean All

All:
	@echo "----------Building project:[ TestingTheImpossible - Debug ]----------"
	@cd "TestingTheImpossible" && "$(MAKE)" -f  "TestingTheImpossible.mk"
clean:
	@echo "----------Cleaning project:[ TestingTheImpossible - Debug ]----------"
	@cd "TestingTheImpossible" && "$(MAKE)" -f  "TestingTheImpossible.mk" clean
